const data = [
  {
  id: 1,
  year: '2017',
  title: 'Every Shadow Has a Name',
  author: 'David Akiba',
  publisher: '',
  role: 'designer',
  url: 'http://www.magcloud.com/browse/issue/1297779',
},{
  id: 2,
  year: '2017',
  title: 'One Hour West',
  author: 'Adam Holtzman',
  publisher: '',
  role: 'designer, editor, artist',
  url: 'http://www.magcloud.com/browse/issue/1219830',
},{
  id: 3,
  year: '2017',
  title: 'flowers',
  author: 'Adam Holtzman',
  publisher: '',
  role: 'designer, editor, artist',
  url: 'http://www.magcloud.com/browse/issue/1347162',
},{
  id: 4,
  year: '2016',
  title: 'Daguerreotype Catalogue - Collection',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: 'https://www.abebooks.com/servlet/BookDetailsPL?bi=21456364804&searchurl=tn%3Dcharles%2Bswedlund%26sortby%3D17&cm_sp=snippet-_-srp1-_-title4',
},{
  id: 5,
  year: '2016',
  title: 'Daguerreotype Catalogue - Back',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: '',
},{
  id: 6,
  year: '2016',
  title: 'Daguerreotype Catalogue - Covers',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: '',
},{
  id: 7,
  year: '2016',
  title: 'Daguerreotype Catalogue - Forgotton',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: '',
},{
  id: 8,
  year: '2016',
  title: 'Daguerreotype Catalogue - Interior Covers',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: '',
},{
  id: 9,
  year: '2016',
  title: 'Daguerreotype Catalogue - Presentations',
  author: 'Charles Swedlund',
  publisher: 'Anna Press',
  role: 'designer',
  url: '',
},{
  id: 10,
  year: '2016',
  title: 'Received on Earth',
  author: 'David Akiba',
  publisher: '',
  role: 'designer',
  url: 'http://www.magcloud.com/browse/issue/1139147',
},
]

export default data
